version: "3"
services:
  seleniumhub:
    image: selenium/hub:latest
    container_name: seleniumhub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - seleniumhub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4444
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4444
      - SE_NODE_MAX_SESSIONS=5

     
  automation:
    image: automation-test:latest
    container_name: automationtest
    build: .
    shm_size: 2gb
    depends_on:
      - seleniumhub
      - chrome
    environment:
      - HOST_NAME=seleniumhub