version: "3"
services:
  selenium-hub:
  image: selenium/hub
  environment:
    - GRID_TIMEOUT=120
    - GRID_MAX_SESSION=200
    - GRID_NEW_SESSION_WAIT_TIMEOUT=-1
    - GRID_BROWSER_TIMEOUT=120
  ports:
    - "4444:4444"

  chrome:
    image: selenium/node-chrome
    links:
      - selenium-hub:hub
    dns:
      - 8.8.8.8
      - 208.67.222.222
    environment:
      - NODE_MAX_INSTANCES=100
      - NODE_MAX_SESSION=100
    volumes:
      - /dev/shm:/dev/shm
    privileged: true

     
  automation:
    image: automation-test:latest
    container_name: automationtest
    build: .
    shm_size: 2gb
    depends_on:
      - selenium-hub
      - chrome
    environment:
      - HOST_NAME=selenium-hub