# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run docker-compose
      run: docker-compose up --exit-code-from automation
    
    - name: upload artifacts
      if: always()
      uses: actions/upload-artifact@v2
      run: mkdir -p demo/src/test/java/report
      run: echo hello > demo/src/test/java/report/Index.html
      with:
        name: htmlreports
        path: demo/src/test/java/report/Index.html